### ISSUE TITLE
About running errors in training

### ISSUE THREAD

**Issue by 1553545365** [Laiqingsi/CLOCs_LQS#5]
When I meet fellow error,
`2022-03-14 15:50:24,384 INFO Generate output done
Traceback (most recent call last):
File "train.py", line 191, in
eval(fusion_layer, val_data, logf, log_path, epoch, cfg, eval_set, logger)
File "train.py", line 125, in eval
eval_metric=cfg.MODEL.POST_PROCESSING.EVAL_METRIC
File "/home/wenhao/桌面/LQS/CLOCs_LQS/pcdet/datasets/kitti/kitti_dataset.py", line 323, in evaluation
if 'annos' not in self.kitti_infos[0].keys():
IndexError: list index out of range`

And I find that coda in `/CLOCs_LQS/pcdet/datasets/kitti/kitti_dataset.py,line 323,`
`    def evaluation(self, det_annos, class_names, **kwargs):
        if 'annos' not in self.kitti_infos[0].keys():
            return None, {}`
self.kitti_infos is empyt `[ ]` , then self.kitti_infos[0] out of range.Cloud you please tell me how can I solve this error?

**Comment by 1553545365** [comment]
I probably solved the problem, I need update the `DATA_PATH` of `CLOCs_LQS/tool/cfgs/dataset_configs/kitti_dataset.yaml` and `CLOCs_LQS/tool/cfgs/dataset_configs/kitti_dataset-pre-val.yaml`
